# Generated by Django 5.0.4 on 2024-04-09 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Announcement",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("title", models.CharField(max_length=128)),
                ("description", models.CharField(max_length=4096)),
            ],
            options={
                "db_table": "announcements",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Rule",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("description", models.CharField(max_length=4096)),
            ],
            options={
                "db_table": "rules",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Team",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=128, unique=True)),
            ],
            options={
                "db_table": "teams",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("tg_id", models.CharField(max_length=16, unique=True)),
                ("admin", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "users",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="VpnConfig",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("path", models.CharField(max_length=128)),
            ],
            options={
                "db_table": "vpn_configs",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Vulnbox",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("description", models.CharField(max_length=1024)),
            ],
            options={
                "db_table": "vulnboxes",
                "managed": False,
            },
        ),
    ]
